### PR TITLE
when a wm is not currently installed, skip its menu template

### PR DESCRIPTION
**Pull request by antix-skidoo**
bin/desktop-menu (Line 299)

### CODE REVIEW

**Review by antiX-Dave — CHANGES_REQUESTED** [review]
How come such sections are removed?

> if Var.Menu_ID == '1':
       write_to_file((Var.Menu_Start % (SUB_ORDER.sub0, SUB_ORDER.sub1,SUB_ORDER.sub2)).encode(encoding))
   else:


This breaks the menu building system for any window manager that requires a name, icon, menu id. Openbox and Blackbox are examples of such window managers.

Also is it safe to assume that 
USER_HOME+"/"+Var.Conf_Dir+"/"+Var.App_File
exists? Does it really not need the check to see if it is there or not? I think if the file is not there it is ok, but if the directory is not then it fails.

**Comment by antix-skidoo** [comment]
What I think happened: I forgot to PULL from github remote before i PUSHED. The edit wasn't intended to _remove_ any existing lines; I was just working from an older copy of the file (before those lines had been added). I've re-uploaded and the side-by-side shown on github for the pull request now matches what I had intended.

Before this patch, on a antiX-full system with jwm removed, console output for each "desktop-menu --write-out-global" operation showed
> Writing Menu: jwm
> sh: 1: jwm: not found

**Comment by antix-skidoo** [comment]
Is the github copy of the desktop-session-antix fileset up-to-date with the fileset anticapitalista has packaged?

Asking because several files in the github fileset seem to contain now-stale menu content. During antiX17 betatesting, I had reported (and anticapitalista had removed) several defunct destination URLs. 

grep the current github fileset:
puppy.b0x.me/wiki/doku.php?id=jwm
fluxbox-wiki.org/index.php/Fluxbox-wiki
ktsuss
roxterm

I'm guessing (haven't checked) that the now-stale menu entries have been updated only within the files provided by the individual "desktop-defaults-jwm|icewm|fluxbox" packages.
-=-
Upon installation of updated "desktop-session-antix" package, the files which were provided by other packages get overwritten? and users suddenly have some non-working menu entries (launcher execstrings trying to invoke nonexistent ktsuss, roxterm, etc)?

**Comment by antiX-Dave** [comment]
I am not seeing the menu files in this repo.

> $ find ./ |grep "menu"
   ./desktop-directories/desktop-menu-personal.directory
   ./desktop-directories/desktop-menu-audio-video.directory
   ./desktop-directories/desktop-menu-development.directory
   ./desktop-directories/desktop-menu-menu.template
   ./desktop-directories/desktop-menu-internet-and-network.directory
   ./desktop-directories/desktop-menu-accessories.directory
   ./desktop-directories/desktop-menu-menu-applications.directory
   ./desktop-directories/desktop-menu-education.directory
   ./desktop-directories/desktop-session-menu.template
   ./desktop-directories/desktop-defaults-menu.template
   ./desktop-directories/desktop-menu-office.directory
   ./desktop-directories/desktop-menu-system.directory
   ./desktop-directories/desktop-menu-network.directory
   ./desktop-directories/desktop-menu-hardware.directory
   ./desktop-directories/desktop-menu-accessibility.directory
   ./desktop-directories/desktop-menu-graphics.directory
   ./desktop-directories/desktop-menu-antiX.directory
   ./desktop-directories/desktop-menu-game.directory
   ./desktop-directories/desktop-menu-settings.directory
   ./bin/desktop-menu-places
   ./bin/desktop-menu
   ./menus
   ./menus/desktop-menu.menu
   ./menus/user-dirs.conf
   ./menus/TCM-MENU.menu
   ./desktop-session-lib/desktop-session-menu-window
   ./desktop-session-lib/desktop-session-update-wm-menus
   ./desktop-menu
   ./desktop-menu/.fluxbox
   ./desktop-menu/.fluxbox/menu-applications
   ./desktop-menu/.icewm
   ./desktop-menu/.icewm/menu-applications
   ./desktop-menu/.jwm
   ./desktop-menu/.jwm/menu-applications
   ./desktop-menu-apt-update
   ./apt.conf.d/99-update-menus
   ./desktop-session/wm-menus
   ./desktop-session/wm-menus/RAW-wm-menu
   ./desktop-session/wm-menus/icewm-wm-menu
   ./desktop-session/wm-menus/jwm-wm-menu
   ./desktop-session/wm-menus/fluxbox-wm-menu
   ./desktop/update-menu.desktop

But there are so many places to look...
They are in the various desktop-defaults packages.
Istm that the window manager specific items maybe should move over to the appropriate desktop-defaults-*wm packages. 
That is assuming the package structure is the same as the github repo. I have not checked this yet.

Do you have a specific link / find of the menu files in question after syncing the repo locally?

**Review by antiX-Dave — APPROVED** [review]
Seems the same now except the part to check if the window manager is installed

**Comment by anticapitalista** [comment]
I added the missing files from Dave's changes.
antix-skidoo - check you don't have the old files in your local repo. The new repo here definitely does not have old menus.

**Comment by antix-skidoo** [comment]
Here are screen captures of what I'm (still, tonight) seeing, finding in search results, for the antiX-Linux/desktop-session-antix repository:
https://vgy.me/s4Bx2w.png
https://vgy.me/EL4MPB.png
https://vgy.me/MNR6mw.png
https://vgy.me/jrpmGn.png
references to "ktsuss", and references to 404 "dillo ...b0x.me" and "fluxbox-wiki" helplinks that we had weeded out during antiX17 betesting, and references to roxterm (vs lxterminal)

**Comment by anticapitalista** [comment]
antix-skidoo - Now I see. Thanks
Those files are not actually doing anything anymore, except taking up space. Dave - can you confirm?

**Comment by anticapitalista** [comment]
While I'm here.
To avoid clutter in the menus and instead of 'hiding' entries, should be bring back the antiX and/or cli section for the menus under Applications?
For antiX we could include all our apps (cli and gui). 
Do we need a cli section?

**Comment by antix-skidoo** [comment]
aha, they're only used by the "personal menu maker" utility (the one thats write to a "TCM" directory). That helps me to understand how we overlooked them during betatesting.

> To avoid clutter in the menus

I worry that an additional "cli applications" submenu or "antiX apps" submenu) would introduce confusion. Maybe it just seems cluttered, as is, because "System Tools" is such a broadly-scoped category? Feedback from forum users would be insightful toward deciding how to proceed.

**Comment by antiX-Dave** [comment]
The .directory files are used for the xdg menu building system.
They are referenced to get the translations and set the categories by the files in /etc/xdg/menus
1. desktop-menu.menu (which could be used to build the applications menu)
2. TCM.menu (which is used to build the personal menu)
*if* the lxde menu continues to be used then we could trim those down.

The template files I am not certain of. I think at one point they were used to build the menus before packing them on the ISO so it was not necessary to edit all the local menu files. I do not recall making anything that needed a template of the root menu. 
IIRC there was a script to take the template files and make the files found in /usr/share/antiX/localisation/. Maybe BitJam wrote it???
How are the root menus generated now? Are they built on the fly or prebuilt and packaged in another deb? 

As to the cli/antiX submenus. 
Switching the symlink /etc/xdg/menus/applications.menu  from pointing to lxde-applications.menu to desktop-menu.menu would open that up to being generated in the applications submenu. 
This is one of the reasons why I did some picking and choosing from lxde and xfce menu systems to build the desktop-menu.menu file and the .directory files in desktop-directories.
Then any "antiX" app with a desktop file would need "X-antiX;" in the Categories: line; which should make it fairly simple to maintain such a submenu.

Currently add-desktop.desktop and remove-desktop.desktop have the X-antiX; entry therefor you can see what It would look like by doing as root
cd /etc/xdg/menus
rm applications.menu
ln -s desktop-menu.menu applications.menu
/usr/local/lib/desktop-menu/desktop-menu-apt-update force
and viewing the applications submenu.

**Comment by antix-skidoo** [comment]
desktop-defaults-icewm
desktop-defaults-jwm
desktop-defaults-fluxbox
each provide a rootmenu, e.g.
https://github.com/antiX-Linux/desktop-defaults-fluxbox/blob/master/skel/.fluxbox/menu

Additionally, my tailored-for-antiX fluxbox package currently provides
https://github.com/antix-skidoo/fluxbox/blob/master/debian/fluxbox.menu-user
(necessary b/c without it, betatesters and upgraders wouldn't be exposed to its expanded functionality)

**Comment by antix-skidoo** [comment]
cd /usr/local
sudo grep -inr 'menu[.]template'  <<<<<<< TOO STRICT
sudo grep -inr 'menu.template'
^---------- on an antiX17-full system ------v

/usr/local/bin/desktop-menu
/usr/local/bin/desktop-menu-places
(provided by pkg "desktop-session-antix")

/usr/local/bin/menu-manager.sh
(provided by pkg "menu-manager-antix")

I found nothing elsewhere (checked /etc, /bin, /sbin, /lib ...)

**Comment by antiX-Dave** [comment]
It seems that the later grep is picking up the / in a path or an _ in a variable
desktop-menu menu/template
> for line in open("/usr/share/desktop-menu/templates/"+DESKTOP+".template", "r").xreadlines():

desktop-menu-places (Note currently not used and I am not sure on the level of functionality... was made to make a sub menu for recent files)
> MENU_TEMPLATE_DIR="/usr/share/desktop-menu/templates"

menu-manager is also a location variable like desktop-menu-places
> WINDOW_MANAGER_MENU_TEMPLATES=/usr/share/desktop-menu/templates

So those template files are seemingly not in use anywhere.

**Pull request merged**
